# Minimal GitHub Pages (Jekyll) config
# Excludes local Python virtualenvs that caused the build error.
theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag

exclude:
  - venv
  - .venv
  - node_modules
  - vendor
  - vendor/bundle
  - .github
  - __pycache__
  - "*.pyc"
