export const DEFAULT_TECHNOLOGY_TERMS = [
  "Artificial Intelligence",
  "AI",
  "Machine Learning",
  "Blockchain",
  "Internet of Things",
  "IoT",
  "Digital Twin",
  "5G",
  "Robotics",
  "Autonomous Systems",
  "Automation",
  "Virtual Reality",
  "Augmented Reality",
  "Cloud Computing",
  "Edge Computing",
  "Fog Computing",
  "Big Data Analytics"
];

export const GERMAN_TECHNOLOGY_TERMS = [
  "Künstliche Intelligenz",
  "KI",
  "Maschinelles Lernen",
  "Blockchain-Technologie",
  "Internet der Dinge",
  "Digitaler Zwilling",
  "5G-Konnektivität",
  "Robotik",
  "Autonome Systeme",
  "Automatisierung",
  "Virtuelle Realität",
  "Erweiterte Realität",
  "Cloud-Computing",
  "Edge-Computing",
  "Fog-Computing",
  "Big-Data-Analytik"
];

export const SPECIALIZED_TECHNOLOGY_TERMS = [
  "BERT",
  "GPT-4",
  "Transformer Models",
  "Random Forest",
  "Gradient Boosting",
  "XGBoost",
  "LightGBM",
  "CatBoost",
  "Support Vector Machines",
  "K-Nearest Neighbors",
  "Naive Bayes",
  "Convolutional Neural Networks",
  "Recurrent Neural Networks",
  "Long Short-Term Memory",
  "Generative Adversarial Networks",
  "Reinforcement Learning",
  "Q-Learning",
  "Federated Learning",
  "Edge AI",
  "AutoML",
  "Robotic Process Automation",
  "Digital Twin Platforms",
  "Additive Manufacturing",
  "ARKit",
  "ARCore",
  "Unity XR",
  "AWS IoT Core",
  "Azure Digital Twins",
  "Google Cloud AutoML",
  "Kubernetes",
  "Docker",
  "Microservices",
  "Serverless Functions",
  "IBM Watson",
  "Oracle Autonomous Database",
  "SAP Leonardo",
  "Snowflake",
  "Databricks",
  "Apache Spark",
  "Hadoop",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "OpenAI API"
];
